config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|es/ do
    devise_for :users, controllers: { registrations: "registrations" }

    root 'home#show'

    get "species/autocomplete"
    get "species/visor"
    get "home/contact_us"
    get "home/about_us"
    get "home/publish"
    get "home/api"
    get "home/terms"
    post "home/send_contact_form"
    post "users_layers/load_layer"
    post "users_layers/pause_layer"
    post "users_layers/send_layer"
    post "reports/update_record"
    post "species/set_species"
    post "records/report_record"
    post "records/edit_record"
    post "records/new_form"
    post "records/show"
    post "species/species_info"
    post "records/send_report_record"
    post "models/load_initial_model"
    post "models/get_thresholds"
    post "models/get_hypotheses"
    post "models/download_model"
    post "models/download_terms"
    post "models/models_stats"
    get "models/metadata"
    get "records/records_metadata/:id" => "records#records_metadata", as: "records_metadata"
    get "species/search"
    post "ratings/rate_model"
    get "eco_variables/eco_variables_search"
    post "eco_variables/add_ecological_variable"
    get "species/:id/get_species_records" => "species#get_species_records"
    post "records/new_record"
    post "records/new_report"
    post "records/update_record"
    post "tasks/add_tasks"
    post "tasks/finish_task"
    post "tasks/tasks_by_group"
    post "tasks/tasks_by_user"
    post "groups_species/species_by_group"
    post "groups_species/update_groups_species"
    post "groups/bulk_group_email"
    post "groups/invite_user"
    post "groups/suggest_group"
    post "groups_users/users_by_group"
    post "groups_users/update_groups_user"
    post "users/send_message_to_user"
    post "groups/group_activity"
    post "home/upload_model"
    post "species/filter"
    get "geoserver/wms"
    get "geoserver/thumb"
    get "geoserver/continuous_thumb"
    get "geoserver/zip"
    get 'atlas/:filename', to: 'downloads#download'
    get '/downloads/generate_report', to: 'downloads#generate_report'
    get '/users', to: redirect('/%{locale}/users/sign_up')

 
    resources :users, :only => [:show]
    resources :groups, :only => [:index, :show, :update]
    resources :info, :only => [:index]
    resources :groups_species, :only => [:index, :create]
    resources :groups_users, :only => [:index, :create, :destroy]
    resources :tasks, :only => [:index, :create, :destroy]
    resources :ratings, :only => [:destroy]
    resources :models do
      member do
        get :metadata
      end
    end
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
	include UsersHelper

	def autocomplete
	    species = Species.search(query: params[:query])
	    result = species.collect do |t|
	      { sci_name: t.sci_name, id: t.id }
	    end
	    render json: result
  	end

  def visor
    @skip_footer = true
  end

  def search
    begin
      species = Species.search(params)
      if species.blank?
        species = { species: "Not found", taxID: 0 }
      end
      render json: species
    rescue => e
      logger.error "#{e.message} #{e.backtrace}"
      err_msg = e.message.tr(?',?").delete("\n")
        render :js => "alertify.alert('Ha ocurrido un error en la búsqueda. #{err_msg}');"
      end
  end

  def filter
    @alerts_to_show = []
    begin
      @species = Species.filter(params)
    rescue => e
      logger.error "#{e.message} #{e.backtrace}"
      @alerts_to_show.push({
        "message" => t('biomodelos.visor.search.error'),
        "type" => 'error'
      })
    end
    respond_to do |format|
      format.js
    end
  end

  def set_species
    begin
      @can_edit = false
      if params[:species_id] == "0"
        render :js => "alertify.alert('La especie #{params[:query]} no está disponible.');"
      else
        if user_signed_in?
          @can_edit = can_edit(current_user.id, params[:species_id])
        end
        #TO DO: get species and find if it's empty (id doesn't exist) or not.
        @species_id = params[:species_id]
        @species_name = Species.find_name(params[:species_id])
        @records_number = Model.valid_records_number(params[:species_id])
        @approved_model = Model.get_valid_model(params[:species_id])
        respond_to do |format|
          format.js
        end
      end
    rescue => e
      logger.error "#{e.message} #{e.backtrace}"
      err_msg = e.message.tr(?',?").delete("\n")
      render :js => "alertify.alert('Ha ocurrido un error consultando la especie. #{err_msg}');"
    end
	end

	def get_species_records
		begin
			if !params[:inGroup].blank? && params[:inGroup]
				records = Species.group_records(params[:id])
			else
				records = Species.records(params[:id])
			end
			render json: records
		rescue => e
			logger.error "#{e.message} #{e.backtrace}"
			err_msg = e.message.tr(?',?").delete("\n")
	    	render :js => "alertify.alert('Ha ocurrido consultando los registros. #{err_msg}');"
	    end
	end

	# Sets the statistics info for the species, sorting and filtering the cover's data
    #
	def species_info
		begin
			@eoo = Model.eoo(params[:species_id])
			@rpa = Model.rpa(params[:species_id])
			@forest_loss = Model.forest_loss(params[:species_id])
			@forest_loss["years"] = []
			@forest_loss["values"] = []
			@forest_loss.keys.sort!.select do |key|
				matches = key.match(/statForestLoss([0-9]+)$/)
				unless matches.nil?
					if (matches[1].to_i >= 90)
						@forest_loss["years"].unshift("19#{matches[1]}")
						@forest_loss["values"].unshift(@forest_loss[key])
					else
						@forest_loss["years"].push("20#{matches[1]}")
						@forest_loss["values"].push(@forest_loss[key])
					end
				end
			end
			@forest_loss["years"] = @forest_loss["years"].to_json.html_safe
			@forest_loss["values"] = @forest_loss["values"].to_json.html_safe
			@all_covers = Model.covers(params[:species_id])
			# Sort the covers by value
			@covers = nil
			if !@all_covers.blank?
				@covers =  Hash[@all_covers.select{|k, v| v && v!= 0 && k != "modelID" && k!= "modelLevel"}.sort_by{ |k, v| v }.reverse]
			end

			respond_to do |format|
	      		format.js
	    	end
	    rescue => e
	    	logger.error "#{e.message} #{e.backtrace}"
			err_msg = e.message.tr(?',?").delete("\n")
			render :js => "alertify.alert('Se ha producido un error al consultar las estadísticas. #{err_msg}');"
	    end
	end
end

app/helpers/species_helper.rb
module SpeciesHelper
	def get_species_name
  		Species.uniq.pluck(:sci_name)    
	end

	def is_integer_num(parameter)
    	!!(parameter =~ /\A[-+]?[0-9]+\z/)
    end

    def model_title_thumb(modelStatus, published)
    	if modelStatus == 'pendingValidation' && published
    		return I18n.t('biomodelos.visor.hypotheses.pending_and_published_thumb')
    	elsif modelStatus == 'pendingValidation' && !published
    		return I18n.t('biomodelos.visor.hypotheses.pending_thumb')
    	elsif modelStatus == 'Valid' && published
    		return I18n.t('biomodelos.visor.hypotheses.valid_published_thumb')
    	elsif modelStatus == 'Valid' && !published
    		return I18n.t('biomodelos.visor.hypotheses.valid_thumb')
		end	
    end
end

app/views/species/_species_contributions.html.erb
		<div class="cvcolumn">
			<!-- <div class="followstate fright"><div class="follow siguiendo">siguiendo</div></div> -->
			<p><%= t('biomodelos.visor.contributions.text_1') %></p>
		</div>
		<h2><%= t('biomodelos.visor.contributions.model_development') %></h2>

		<div class="steptitle">1. <%= t('biomodelos.visor.contributions.statistical_model') %></div>
		<div class="dinblock">
			<% if continuous_t %>
				<div class="editthumb">
					<%= image_tag(model_thumb(continuous_t)) %>
				</div>
			<div class="editactions clearfix">
			<%= button_to models_download_terms_path(:zip_url => model_zip(continuous_t), :box => 1, :model_id => continuous_t.modelID, :species_id => @species_id), {:class => 'pad3', :title => t('biomodelos.visor.hypotheses.download_tt'), :rel => "tooltip", :remote => true} do %>
						<%= image_tag("downicon.png") %>
					<% end %>
					<%= link_to "/#{I18n.locale}/models/#{continuous_t.modelID}/metadata",  target: "_blank", title: t('biomodelos.visor.hypotheses.metadata_tt'), rel: "tooltip"  do %>
						<%= image_tag("metaicon.png") %>
					<% end %>
					<%= hidden_field_tag 'continuous_t_url', model_layer(continuous_t).html_safe %>
					<button class="newgrbtn btnemergencia" id="cbt_editBtn"><%= t('biomodelos.visor.contributions.edit_btn') %></a>
			<% else %>
				<div class="editthumb">
					<%= image_tag("nomap.png") %>
				</div>
				<div class="editactions clearfix">
			<% end %>
			<% if zero_t %>
				<%= hidden_field_tag 'zero_t_url', model_layer(zero_t).html_safe %>
			<% else %>
				<%= hidden_field_tag 'zero_t_url' %>
			<% end %>
			<% if ten_t %>
				<%= hidden_field_tag 'ten_t_url', model_layer(ten_t).html_safe %>
			<% else %>
				<%= hidden_field_tag 'ten_t_url' %>
			<% end %>
			<% if twenty_t %>
				<%= hidden_field_tag 'twenty_t_url', model_layer(twenty_t).html_safe %>
			<% else %>
				<%= hidden_field_tag 'twenty_t_url' %>
			<% end %>
			<% if thirty_t %>
				<%= hidden_field_tag 'thirty_t_url', model_layer(thirty_t).html_safe %>
			<% else %>
				<%= hidden_field_tag 'thirty_t_url' %>
			<% end %>
			</div>
		</div>
		<div class="dinblock">
			<p class="estadistico"><%= t('biomodelos.visor.contributions.threshold_title') %></p>
			<p><%= t('biomodelos.visor.contributions.threshold_text') %></p>
			<p class="estadistico edicon"><%= t('biomodelos.visor.contributions.tools_title') %></p>
			<p><%= t('biomodelos.visor.contributions.tools_text') %></p>
			<p class="estadistico veicon"><%= t('biomodelos.visor.contributions.variables_title') %></p>
			<p><%= t('biomodelos.visor.contributions.variables_text') %></p>
		</div>
		<div class="steptitle">2. <%= t('biomodelos.visor.contributions.create_your_map') %></div>
		<p><%= t('biomodelos.visor.contributions.create_your_map_text') %></p>
		<div class="editactions clearfix">
			<button class="newgrbtn" id="cbt_crearBtn"><%= t('biomodelos.visor.contributions.create_btn') %></button>
		</div>

		<div class="steptitle">3. <%= t('biomodelos.visor.contributions.publish') %></div>
		<p><%= t('biomodelos.visor.contributions.publish_text') %></p>
		<%= link_to image_tag("uploadicon.png"), home_publish_path %>
		<div class ="termbox"></div>

app/views/species/_species_models.html.erb
<% if @models && !@models.blank? %>
	<p><%= t('biomodelos.visor.hypotheses.text_1') %></p>
	<div class="button-group filter-button-group">
	  <button class="filterbtn <%= !@valid_models.empty? ? 'is-checked' : '' %>" data-filter=".validados"><%= t('biomodelos.visor.hypotheses.validated') %></button>
	  <button class="filterbtn" data-filter=".publicados"><%= t('biomodelos.visor.hypotheses.published') %></button>
	  <button class="filterbtn" data-filter=".estadisticos"><%= t('biomodelos.visor.hypotheses.statistical') %></button>
	  <button class="filterbtn" data-filter=".para-calificar"><%= t('biomodelos.visor.hypotheses.to_rate') %></button>
	  <button class="filterbtn <%= @valid_models.empty? ? 'is-checked' : '' %>" data-filter="*"><%= t('biomodelos.visor.hypotheses.all') %></button>
	</div>

	<div class="grid">

	<% @models.each_with_index do |model, i| %>
		<% tags = model.modelStatus == 'Valid' ? ' validados' : '' %>
		<% tags += model.published && model.modelStatus == 'pendingValidation' ? 'publicados' : '' %>
		<% tags += model.modelStatus == 'Statistic' ? ' estadisticos' : '' %>
		<% tags += model.modelStatus == 'pendingValidation' ? ' para-calificar' : '' %>
		<div class="maparea <%= tags %>">
			<div href="" class="mapthumb">
				<div class="flipper">
					<div class="front2"><%= image_tag(model_thumb(model)) %></div>
					<a class="back2 sp_model_link">
						<%= hidden_field_tag('model_layer', model_layer(model).html_safe) %>
						<div class="titlethumb">
							<%= model_title_thumb(model.modelStatus, model.published) %>
							<%= hidden_field_tag 'txt_model_status', model.modelStatus %>
						</div>
						<div class="citathumb"><b>
							<% if !model.level.blank? %>
						 		<%= t('biomodelos.visor.hypotheses.level') %> <%= model.level %>
						 	<% end %>
						</b></div>
						<div class="infothumb">
							<%= t('biomodelos.visor.hypotheses.rating_mean') %>
							<div class="calificacion"><%= Rating.average_rating(model.modelID) %> <b>(<%= Rating.rating_number(model.modelID) %> <%= t('biomodelos.visor.hypotheses.votes') %>)</b></div>
						</div>
						<div class="infothumb">
							<%= t('biomodelos.visor.hypotheses.downloads_number') %>
							<div class="calificacion"><%= Download.downloads(model.modelID) %></div>
						</div>
						<div class="citathumb lhlow"><%= model.citation.blank? ? "": model.citation %></div>
						<div class="commons">
							<% if model.license == 'by' %>
								<%= image_tag("cc1.png") %>
								<%= image_tag("cc2.png") %>
							<% elsif model.license == 'by-sa' %>
								<%= image_tag("cc1.png") %>
								<%= image_tag("cc2.png") %>
								<%= image_tag("cc4.png") %>
							<% elsif model.license == 'by-nc' %>
								<%= image_tag("cc1.png") %>
								<%= image_tag("cc2.png") %>
								<%= image_tag("cc3.png") %>
							<% elsif model.license == 'by-nc-sa' %>
								<%= image_tag("cc1.png") %>
								<%= image_tag("cc2.png") %>
								<%= image_tag("cc3.png") %>
								<%= image_tag("cc4.png") %>
							<% elsif model.license == 'cc-zero' %>
								<%= image_tag("cc5.png") %>
							<% end %>
						</div>
					</a>
				</div>
			</div>
			<div class="mmicon clearfix">
				<%= button_to models_download_terms_path(:zip_url => model_zip(
				model), :box => 2, :model_id => model.modelID , :species_id => @species_id), {:class => 'pad3', :title => t('biomodelos.visor.hypotheses.download_tt'), :rel => "tooltip", :remote => true} do %>
						<%= image_tag("downicon.png") %>
					<% end %>
				<%= link_to "/#{I18n.locale}/models/#{model.modelID}/metadata", target: "_blank", title: t('biomodelos.visor.hypotheses.metadata_tt'), rel: "tooltip", class: "pad3"  do %>
					<%= image_tag("metaicon.png") %>
				<% end %>
				<% if user_signed_in? && can_edit %>
					<div class="user_star">
						<%= hidden_field_tag('myscore', ratings[model.modelID], :class => 'myscore') %>
						<%= hidden_field_tag('model', model.modelID, :class => 'model_id' )  %>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>

	</div>

<% else %>
	<p><%= t('biomodelos.visor.hypotheses.text_2_html') %></p>
		<div class="maparea">
			<div href="" class="mapthumb">
				<div class="flipper">
					<div class="front2"><%= image_tag("nomap2.png") %></div>
					<div class="back2">
						<div class="titlethumb">
							<%= t('biomodelos.visor.hypotheses.no_model') %>
						</div>
					</div>
				</div>
			</div>
			<div class="mmicon clearfix">
			</div>
		</div>
<% end %>
<div class ="termbox2"></div>

<!-- <h3>FORO <i>Aglaiocercus coelestis</i></h3>
<form action="">
	<textarea name="" id="" cols="30" rows="4" placeholder="Foro exclusivo para comentar las hipótesis de distribución disponibles para esta especie."></textarea>
</form>
<input type="submit" value="COMENTAR"></input>
<div class="clearfix"></div>
<div class="notif">
	<%= image_tag("nouserthumb.png") %>
	<a class="foroname" href="">Victor Setina Liz</a>
	<h6 class="fechanotif">18 · Jun · 2016 - 16:36</h6>
	<p>Fue aceptado en el grupo <a href="">Mamíferos de Colombia</a></p>
	<div class="foroactions">
		<a href="">responder</a>
		<a href="">editar</a>
		<a href="">borrar</a>
	</div>
</div>
<div class="notif reply">
	<%= image_tag("userthumbp.png") %>
	<a class="foroname" href="">César Gutiérrez</a>
	<h6 class="fechanotif">18 · Jun · 2016 - 16:36</h6>
	<p>Fue aceptado en el grupo <a href="">Mamíferos de Colombia</a></p>
	<div class="foroactions">
		<a href="">responder</a>
		<a href="">borrar</a>
	</div>
</div> -->
<script type="text/javascript">
/* Rating */
var raty_icon_path = "/assets/raty/lib/images";
$('.user_star').raty({
	path: raty_icon_path,
	hints: ['<%= t('biomodelos.visor.hypotheses.rating_0_hint') %>', '<%= t('biomodelos.visor.hypotheses.rating_1_hint') %>', '<%= t('biomodelos.visor.hypotheses.rating_2_hint') %>', '<%= t('biomodelos.visor.hypotheses.rating_3_hint') %>', '<%= t('biomodelos.visor.hypotheses.rating_4_hint') %>'],
	cancel: true,
	cancelHint:   '<%= t('biomodelos.visor.hypotheses.rating_delete') %>',
	score:  function() {
		return $(this).find('.myscore').val();
	},
	click: function(score, evt) {
		model_clicked_id = $(this).find('.model_id').val();
		if(evt.currentTarget.className === "raty-cancel")
		{
			if(<%= user_signed_in? %>){
				$.ajax({
					type: "DELETE",
					url: "/ratings/destroy",
					data: { model_id: $(this).find('.model_id').val(), uid: $('#bio_user_id').val()}
				});
			}
		}
		else{

			$.ajax({
				type: "POST",
				url: "/ratings/rate_model",
				data: { model_id: $(".model_id[value='"+model_clicked_id+"']").val(), species_id: $("#species_id_field").val(), score: score,},
				success: function(data){

				},
				error: function(data){
					alertify.alert("<%= t('biomodelos.visor.hypotheses.rating_error') %>");
				}
			});

		}
	}
});

// init Isotope
var $grid = $('.grid').isotope({
  filter: $('.button-group .is-checked').attr('data-filter')
});

$('.filter-button-group').on( 'click', 'button', function() {
  var filterValue = $(this).attr('data-filter');
  $grid.isotope({ filter: filterValue });
});

// change is-checked class on buttons
$('.button-group').each( function( i, buttonGroup ) {
  var $buttonGroup = $( buttonGroup );
  $buttonGroup.on( 'click', 'button', function() {
    $buttonGroup.find('.is-checked').removeClass('is-checked');
    $( this ).addClass('is-checked');
  });
});
</script>

app/views/species/set_species.js.erb
$(document).ready(function(){
	<% if !params[:species_id].blank? && is_integer_num(params[:species_id]) && params[:species_id] != 0 %>
    $("#species_id_field").val("<%= params[:species_id] %>");
    $(".spname").html("<%= @species_name %>");
    $("#info_species_name").html("<%= @species_name %>");
    $("#info_records_number").html("<%= @records_number %>");
    $("#info_records_metadata").html('<%= link_to t("biomodelos.visor.statistics.records_metadata"), records_metadata_path(:id => params[:species_id]), target: "_blank" %>');
    <% if @approved_model.blank? %>
      $(".vbtnhipo").removeClass('btn2Top').addClass('btn1Top');
    <% else %>
      $(".vbtninfo").show();
      $(".vbtnhipo").removeClass('btn1Top').addClass('btn2Top');
      $("#valid_model_info").text("<%= @approved_model.modelID %>")
    <% end %>
    /* Clears layers */
		_BioModelosVisorModule.unloadAllLayers();
		/* Clears edition tools */
		$(".btnedicion").hide();
		if($(".cajitaeditar").is(":visible")){
				$(".btnedicion").click();
		}
		/* Loads records */
		_BioModelosVisorModule.getSpeciesRecords("<%= params[:species_id] %>", <%= @can_edit %>);
		$(".btnregistros").show();
		if(!$(".cajaregistros").is(":visible")){
			$(".btnregistros").click();
		}
		_speciesFunctionsModule.resetRecordsFilters();
		/* Shows main toolbar buttons */
		$(".vbtnhipo").show();
		/* Loads initial model */
		$.post( "/"+ $("#locale_field").val() +"/models/load_initial_model", { species_id: <%= params[:species_id] %>});
		/* Dynamically loads the edition tools if the user can edit */
		<% if user_signed_in? && @can_edit %>
			_utils_bio_module.compileDynamicAngularContent("#visCntrl", $('#edit_model_btn'), '<div ng-click="edit=!edit" title="<%= t("biomodelos.visor.tooltip.edit_btn") %>" rel="tooltip" class="visorbtn vbtnedit btn3Top" selectable></div>');
			$(".vbtnedit").show();
      <% if @approved_model.blank? %>
        $(".vbtnedit").removeClass('btn3Top').addClass('btn2Top');
      <% else %>
        $(".vbtnedit").removeClass('btn2Top').addClass('btn3Top');
      <% end %>
			_utils_bio_module.compileDynamicAngularContent("#visCntrl", $("#edit_box_btn"),'<div ng-click="editar=!editar" class="btnedicion" selectable><%= t("biomodelos.visor.edition_box.title") %></div>');
			_utils_bio_module.compileDynamicAngularContent("#visCntrl", $("#edit_tools_box"), '<div ng-show="editar" class="cajitaeditar"><%=j render 'species/species_edition' %></div>');
			$('#add_records_box').html('<%=j render partial: 'species_edition_new_records' %>');
		<% else %>
			$('#edit_model_btn').html('');
			$("#edit_box_btn").html('');
			$("#edit_tools_box").html('');
			$('#add_records_box').html('');
		<% end %>
		$(".spname").show();
		if($(".cajasearch").is(":visible"))
			$("#clsSearchBox").click();
	<% else %>
		$("#species_id_field").val(0);
		/* Clears layers */
		_BioModelosVisorModule.unloadAllLayers();
		$(".btnedicion").hide();
		$(".spname").hide();
		$(".modelname").hide();
		if($(".cajitaeditar").is(":visible")){
				$(".btnedicion").click();
		}
		if($(".cajaregistros").is(":visible")){
			$(".btnregistros").click();
		}
		$(".btnregistros").hide();
	<% end %>
});

app/views/species/visor.html.erb
<% if !params[:search].blank? && params[:search] == "1" %>
      <script>
          $(document).ready(function(){
          	$(".vbtnfind").click();
          });
      </script>
<% elsif !params[:species_id].blank? && is_integer_num(params[:species_id]) %>
      <script>
          //Unique URL for each species
          $(document).ready(function(){
	          $.ajax({
	                          type: "POST",
	                          url: "/" + $("#locale_field").val() + "/species/set_species",
	                          data: { species_id: <%=j params[:species_id]%> }
	          });
	      });
      </script>
<% end %>
<div class="mapcontainer" id="map"></div>
<div class="reportBox"></div>
<div id="visCntrl" ng-controller="visorCtrl">
  <button id="model-status-btn" class="arrow-status"></button>
	<div class="spname"></div>
	<%= hidden_field_tag 'species_id_field'%>
	<div class="modelname" title='<%= t('biomodelos.visor.tooltip.model_name') %>' rel="tooltip"> <!-- agregar en Continuo class: gradient --></div>
	<div id="layerbtn" title='<%= t('biomodelos.visor.tooltip.layer_btn') %>' rel="tooltip" class="visorbtn"></div>
	<div ng-click="find=!find" title='<%= t('biomodelos.visor.tooltip.find_btn') %>' rel="tooltip" class="visorbtn vbtnfind" selectable></div>
	<div ng-click="info=!info" title='<%= t('biomodelos.visor.tooltip.info_btn') %>' rel="tooltip" class="visorbtn vbtninfo btn1Top" selectable></div>
	<div ng-click="hipotesis=!hipotesis" title='<%= t('biomodelos.visor.tooltip.hipo_btn') %>' rel="tooltip" class="visorbtn vbtnhipo btn2Top" selectable></div>
	<div id="edit_model_btn"></div>

	<div ng-show="find" class="cajavisor cajasearch">
		<%= render 'species/species_browser' %>
	</div>

	<div ng-show="info" class="cajavisor infocaja">
		<%= render 'species/species_info' %>
	</div>


	<div ng-show="hipotesis" class="cajavisor hipotesis">
		<div class="vcbase">
			<h1><%= t('biomodelos.visor.hypotheses.title') %></h1>
			<a ng-click="hipotesis=!hipotesis" class="closevb" id="clsModelsBox">x</a>
		</div>
		<div class="cvcolumn">
<!-- 			<div class="followstate fright">
				<a href="" class="follow invisible">seguir</a>
				<div class="follow siguiendo">siguiendo</div>
			</div> -->
			<div id="hipotesisbox_content"></div>
		</div>
	</div>

	<% if user_signed_in? %>
		<div ng-show="edit" class="cajavisor editbox">
			<div class="vcbase">
				<h1><%= t('biomodelos.visor.contributions.title') %></h1>
				<a ng-click="edit=!edit" class="closevb" id="clsEditBox">x</a>
			</div>
			<div id="editbox_content"></div>
		</div>
	<% end %>

	<div ng-click="registros=!registros" class="btnregistros" selectable><%= t('biomodelos.visor.records.title') %></div>

	<div ng-show="registros" class="cajaregistros" id="registros_div">
		<%= render partial: 'species/species_records' %>
		<div class="littleline"></div>
		<div class="foreditors" id="add_records_box"></div>
	</div>

	<% if user_signed_in? %>
			<div id="edit_box_btn"></div>
	<% end %>

	<% if user_signed_in? %>
		<div id="edit_tools_box"></div>
	<% end %>

	<div id="show_record_box"></div>
	<div id="new_record_box"></div>
	<div id="model-status-info"></div>

</div>

<%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+ Rails.application.credentials.dig(:google_maps, :GOOGLE_MAPS_KEY) %>
<%= javascript_include_tag 'Google.js' %>
<%= javascript_include_tag 'biovisor' %>

<div class="visorfooter">
			<a href="http://www.humboldt.org.co" class="humboldtft" target="_blank">
				<div class="humbname">
					<h1><%= t('biomodelos.footer.institute_html') %></h1>
				</div>
			</a>
			<nav>
				<ul id="subnav">
					<!-- <li>
						<%= link_to 'Tutorial', root_path %>
					</li> -->
				</ul>
				<ul id="subnav">
					<li>
						<%= link_to t('biomodelos.footer.info'), info_index_path %>
					</li>
				</ul>
				<%= image_tag("logolba.png") %>
			</nav>
</div>

<script>
$(document).ready(function(){
	HomeControllerModule.typeahead_f();

 	$(".leaflet-control-layers").removeClass("leaflet-control-layers-expanded");

	$("#layerbtn").on("click",function(){

	if($("#layerbtn").hasClass("vbtnact")){
	 $("#layerbtn").removeClass("vbtnact");
	 }
	else {
	 	$("#layerbtn").addClass("vbtnact");
	}

	if($(".leaflet-control-layers").hasClass("leaflet-control-layers-expanded")){
	 	$(".leaflet-control-layers").removeClass("leaflet-control-layers-expanded");
	}
	else {
	 	$(".leaflet-control-layers").addClass("leaflet-control-layers-expanded");
	}
	});

	$(".taxbtn").click(function(e){
		$(this).toggleClass("taxbtnact");
		e.preventDefault();
	});
});

</script>