config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|es/ do
    devise_for :users, controllers: { registrations: "registrations" }

    root 'home#show'

    get "species/autocomplete"
    get "species/visor"
    get "home/contact_us"
    get "home/about_us"
    get "home/publish"
    get "home/api"
    get "home/terms"
    post "home/send_contact_form"
    post "users_layers/load_layer"
    post "users_layers/pause_layer"
    post "users_layers/send_layer"
    post "reports/update_record"
    post "species/set_species"
    post "records/report_record"
    post "records/edit_record"
    post "records/new_form"
    post "records/show"
    post "species/species_info"
    post "records/send_report_record"
    post "models/load_initial_model"
    post "models/get_thresholds"
    post "models/get_hypotheses"
    post "models/download_model"
    post "models/download_terms"
    post "models/models_stats"
    get "models/metadata"
    get "records/records_metadata/:id" => "records#records_metadata", as: "records_metadata"
    get "species/search"
    post "ratings/rate_model"
    get "eco_variables/eco_variables_search"
    post "eco_variables/add_ecological_variable"
    get "species/:id/get_species_records" => "species#get_species_records"
    post "records/new_record"
    post "records/new_report"
    post "records/update_record"
    post "tasks/add_tasks"
    post "tasks/finish_task"
    post "tasks/tasks_by_group"
    post "tasks/tasks_by_user"
    post "groups_species/species_by_group"
    post "groups_species/update_groups_species"
    post "groups/bulk_group_email"
    post "groups/invite_user"
    post "groups/suggest_group"
    post "groups_users/users_by_group"
    post "groups_users/update_groups_user"
    post "users/send_message_to_user"
    post "groups/group_activity"
    post "home/upload_model"
    post "species/filter"
    get "geoserver/wms"
    get "geoserver/thumb"
    get "geoserver/continuous_thumb"
    get "geoserver/zip"
    get 'atlas/:filename', to: 'downloads#download'
    get '/downloads/generate_report', to: 'downloads#generate_report'
    get '/users', to: redirect('/%{locale}/users/sign_up')

 
    resources :users, :only => [:show]
    resources :groups, :only => [:index, :show, :update]
    resources :info, :only => [:index]
    resources :groups_species, :only => [:index, :create]
    resources :groups_users, :only => [:index, :create, :destroy]
    resources :tasks, :only => [:index, :create, :destroy]
    resources :ratings, :only => [:destroy]
    resources :models do
      member do
        get :metadata
      end
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :groups_users
  has_many :users, through: :groups_users
  #has_many :admin, through: :game_users, ->  where(is_admin: true)
  has_many :admin, -> { where is_admin: true }, class_name: 'GroupsUser'
  
  mount_uploader :logo, GroupLogoUploader

  	def activity
      Group.find_by_sql(
        "(SELECT u.id, u.name user_name,'0' sp_id, '' task_name, gu.created_at updated_at, 'new_user' as tipo
          FROM users u, groups_users gu
          WHERE u.id = gu.user_id AND gu.groups_users_state_id = 1 AND gu.group_id = "+self.id.to_s+"
          ORDER BY gu.created_at DESC 
          LIMIT 15) 

          UNION ALL

        (SELECT u.id, u.name user_name, t.species_id sp_id, tt.name task_name, t.updated_at, 'task_done' tipo
        FROM tasks t, task_types tt, users u
        WHERE t.task_type_id = tt.id AND t.user_id = u.id AND t.group_id = "+self.id.to_s+" AND t.task_state_id = 2
        ORDER BY t.updated_at DESC
        LIMIT 15)
        ORDER BY updated_at DESC
        LIMIT 15")
  	end
end

app/models/groups.rb
class Group < ActiveRecord::Base
	has_many :groups_users
  	has_many :users, through: :groups_users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups = Group.where(:group_state_id => 1)
	end

	def show
		begin
			@group = Group.find(params[:id])
			@tasks = Task.where(:group_id =>  @group.id)
			@species_ids = GroupsSpecies.where(:group_id => @group.id, :groups_species_state_id => 1)
			@group_members_number = GroupsUser.where(:group_id => @group.id, :groups_users_state_id => 1).count
			@group_admins = GroupsUser.where(:group_id => @group.id, :groups_users_state_id => 1, :is_admin => true).joins(:user).order('users.name')
			@groups_species = GroupsSpecies.new
			@current_group_user = false
			@user_group = nil
			@groups_users = GroupsUser.new
			@task = Task.new
			if user_signed_in?
				@user_group = GroupsUser.find_by(group_id: @group.id, user_id: current_user.id)
				@current_group_user = (@user_group && @user_group[:groups_users_state_id] == 1) ? @user_group : nil
			end
	    rescue => e
				logger.error "#{e.message} #{e.backtrace}"
				err_msg = e.message.tr(?',?").delete("\n")
				redirect_to root_path, :flash => { :error => "Ha ocurrido un error: #{err_msg}" }
	    end
	end

	def update
		group_params = params[:group]
	    @group = Group.find(params[:id])
	    @group.name=group_params[:name]
	    @group.message=group_params[:message]
	    @group.logo=group_params[:logo]
	    if @group.save
	      redirect_to group_path(id:params[:id]), :flash => { :notice => "El perfil de grupo ha sido actualizado con éxito." }
	    else
	      redirect_to group_path(id:params[:id]), :flash => { :error => "Ha ocurrido un error actualizando el pefil de grupo" }
	    end
	end

	def group_activity
		@group = Group.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	# Sends an email to every active member of a group.
	#
	def bulk_group_email
	    mails = []
	    group = Group.find(params[:message][:group_id])
	    group_users = GroupsUser.where(:group_id => group.id, :groups_users_state_id => 1)
	    group_users.each do |f|
	      mails.push(f.user.email)
	    end
	    if !params[:message][:message].blank?
	    	GroupMailer.bulk_email_group(params[:message][:message], mails, group.name, current_user.name).deliver_now
	    	redirect_to group_path(id: group.id), :flash => { :notice => "El mensaje ha sido enviado a los miembros del grupo." }
	    else
	    	redirect_to group_path(id: group.id), :flash => { :error => "Debe agregar un mensaje para enviar al grupo." }
	    end
	end

	def suggest_group
		@new_group = SuggestedGroup.new(suggested_group_params)
		if @new_group.valid?
			AdministratorsMailer.group_suggested(current_user, @new_group).deliver_now
			redirect_to groups_path, notice: 'Tu sugerencia ha sido recibida.'
		else
			redirect_to groups_path, :flash => { :error => "Debe llenar todos los campos para sugerir un grupo." }
		end
	end

	def invite_user
		mails = []
	    group = Group.find(params[:message][:group_id])
		mails = params[:message][:email].split(";")
		if !mails.blank? && !params[:message][:message].blank?
			GroupMailer.user_invitation(mails, group, current_user, params[:message][:message]).deliver_now
	    	redirect_to group_path(id: group.id), :flash => { :notice => "El mensaje ha sido enviado a los miembros del grupo." }
		else
			redirect_to group_path(id: group.id), :flash => { :error => "Debe llenar todos los campos para invitar a un experto al grupo." }
		end
	end

	private

		def suggested_group_params
      		params.require(:suggested_group).permit(:name, :moderator, :content)
    	end
end

app/views/groups/_edit_group.html.erb
<h2><%= t('biomodelos.groups.edit.title') %></h2>
<%= simple_form_for @group do |f| %>
	<h3><%= t('biomodelos.groups.edit.group_name') %></h3>
	<%= f.input :name, :maxlength => 50, :placeholder => t('biomodelos.groups.edit.former_name_ph'), :name => "nombre", label: false%>
	<h3>Mensaje del moderador</h3>
	<%= f.input :message, :as => :text, :placeholder => t('biomodelos.groups.edit.former_message_ph'), :input_html => {:maxlength => 300, :cols => "20", :rows => "4"}, :name => "cuerpo", label: false %>
	<h3><%= t('biomodelos.groups.edit.change_photo') %></h3>
	<div class="inputBtnSection ml0">
        <input id="uploadFile" class="disableInputField w203" placeholder="<%= t('biomodelos.publish.select_file_ph') %>" />
	    <label class="fileUpload">
		    <%= f.input :logo, :as => :file, :required => true, label: false, error_html: {:class => 'publierror'}, :input_html => { :id => "uploadBtn", :class => "upload"} %>
		    <span class="uploadBtn"><%= t('biomodelos.groups.edit.upload_photo_btn') %></span>
	    </label>
    </div>
    <div class="clearfix"></div>
    <%= f.submit t('biomodelos.groups.edit.submit_btn'), class: "btngen ml0"%>
    <div id="clsEditGroupBtn"></div>
<% end %>
<script type="text/javascript">
	$(document).ready(function(){
		_utils_bio_module.compileDynamicAngularContent("#perfilCntrl", $("#clsEditGroupBtn"), '<a class="closeedit" ng-click="editgroup=!editgroup">X</a>');
		
		document.getElementById("uploadBtn").onchange = function () {
          document.getElementById("uploadFile").value = this.value;
      	};
	});
</script>

app/views/groups/_groups_activity.html.erb
<h1><%= t('biomodelos.groups.profile.activity_tab') %></h1>
<% @group.activity.each do |activity| %>
	<div class="notif">  
    <% if activity.tipo == 'task_done' %>
    	<%= image_tag(User.find(activity.id).avatarURL.url(:thumb).to_s) %>
    	<h6 class="fechanotif"><%= activity.updated_at.to_time.strftime("%F %R") %></h6>
    	<p><a href="/users/<%= activity.id %>"><%= activity.user_name %></a> <%= t('biomodelos.groups.profile.task_completed') %> <i><%= activity.task_name %></i> <%= t('biomodelos.groups.profile.for_the_species') %> <a class="activity" href="/species/visor?species_id=<%= activity.sp_id %>"><%= Species.find_name(activity.sp_id) %></a></p>
   <% elsif activity.tipo == 'new_user' %>
        <%= image_tag(User.find(activity.id).avatarURL.url(:thumb).to_s) %>
    	<h6 class="fechanotif"><%= activity.updated_at.to_time.strftime("%F %R") %></h6>
    	<p><a href="/users/<%= activity.id %>"><%= activity.user_name %></a> <%= t('biomodelos.groups.profile.joined_group') %></p>
    <% end %>
   	</div>
<% end %> 

app/views/groups/_groups_species.html.erb
<h1><%= t('biomodelos.groups.profile.species_tab') %></h1>
<% if @current_group_user %>
	<a ng-click="sugeridor=!sugeridor; activeButton()" ng-class="{'btnact': isActive}" class="genericbtn"><%= t('biomodelos.groups.species.suggest') %></a>
	<div ng-show="sugeridor" class="sugeridor">
		<%= simple_form_for @groups_species, :remote => true do |f| %>
			<%= text_field_tag :query, '', :id => 'search_form', :placeholder => t('biomodelos.home.search_ph'), :include_blank => false, :rel => 'autocomplete' %>
			<%= f.hidden_field :groups_species_state_id, :value => 2 %>
			<%= f.hidden_field :species_id, :id => "species_id_home" %>
			<%= f.hidden_field :group_id, :id => "group_id_home", :value => @group.id %>
			<%= f.submit "+", :class=> "searchbtnspp bigplus", data: { disable_with: "+" } %>
		<% end %>
	</div>
<% end %>

<div id="group_species_tables"></div>

app/views/groups/_groups_statistics.html.erb
<h1><%= t('biomodelos.groups.profile.statistics_tab') %></h1>

<div class="estadbox">
	<h2><%= t('biomodelos.groups.profile.experts_in_group') %></h2>
	<h6><%= @group_members_number %></h6>
</div>
<div class="estadbox">
	<h2><%= t('biomodelos.groups.profile.species_in_group') %></h2>
	<h6><%= @species_ids.size %></h6>
</div>
<!--<div class="estadbox">
	<h2><%= t('biomodelos.groups.profile.species_with_tasks') %></h2>
	<h6></h6>
</div> 
<div class="estadbox">
	<h2>modelos aprobados</h2>
	<h6><%= @models_approved %></h6>
</div> -->

<!-- <div class="top5">
	<h2>TOP 5 Colaboradores</h2>
	<h3>Aportes</h3>
</div>
<div class="top5users">
	<a href="">Daniel Lopez</a>
	<p>15</p>
</div>
<div class="top5users">
	<a href="">Daniel Lopez</a>
	<p>15</p>
</div>
<div class="top5users">
	<a href="">Daniel Lopez</a>
	<p>15</p>
</div>
<div class="top5users">
	<a href="">Daniel Lopez</a>
	<p>15</p>
</div>
<div class="top5users">
	<a href="">Daniel Lopez</a>
	<p>15</p>
</div> -->

app/views/groups/_groups_tasks.html.erb
<h1 class="tasks"><%= t('biomodelos.groups.profile.tasks_tab') %></h1> 
<% if @current_group_user %>
	<div class="newtask" ng-click="taskbox=!taskbox" rel="tooltip" title="<%= t('biomodelos.tasks.new_task') %>"><%= image_tag("newtask.png") %></div>
	<div class="clearfix"></div>
	<div class="addtask" ng-show="taskbox">
		<%= render partial:'tasks/new_tasks_form', locals: {task: @task, group: @group, group_members: @group_members, group_species: @group_species, current_group_user: @current_group_user} %>	
	</div>
<% end %>
<div class="clearfix"></div>
<div class="colspp tabletit">
	<h2><%= t('biomodelos.tasks.species') %></h2>
</div><!-- 
--><div class="coladv tabletit" rel="tooltip" title="<%= t('biomodelos.tasks.records_task_tt') %>">
	<%= image_tag("regperfil.png") %>
</div><!-- 
--><div class="coladv tabletit" rel="tooltip" title="<%= t('biomodelos.tasks.edition_task_tt') %>">
	<%= image_tag("penperfil.png") %>
</div><!--  
--><div class="coladv tabletit" rel="tooltip" title="<%= t('biomodelos.tasks.covers_task_tt') %>">
	<%= image_tag("veicon2.png") %>
</div><!-- 
--><div class="coladv tabletit" rel="tooltip" title="<%= t('biomodelos.tasks.validation_task_tt') %>">
	<%= image_tag("aprobicon.png") %>
</div><!-- 
--><div class="coladv tabletit" rel="tooltip" title="<%= t('biomodelos.tasks.advance_tt') %>">
	<%= image_tag("percicon.png") %>
</div>
<div id="group_tasks_table"></div>

app/views/groups/_groups_users.html.erb
<h1><%= t('biomodelos.groups.experts.title') %></h1>
<% if @current_group_user %>
	<a ng-click="invitador=!invitador; activeButton()" ng-class="{'btnact': isActive}" class="genericbtn"><%= t('biomodelos.groups.experts.invitation_title') %></a>
	<div ng-show="invitador" class="forms">
		<p class="groupuser"><%= t('biomodelos.groups.experts.invitation_notice') %></p><br/>
		<%= simple_form_for :message, :url =>  groups_invite_user_path, :method => :post do |f| %>
	         <%= f.error_notification %>
	         <%= f.hidden_field :group_id, :value => @group.id %>
	         <%= f.input :email, :maxlength => 500, :placeholder => t('biomodelos.groups.experts.email_ph'), :name => "email", label: false %>
	         <%= f.input :message, :as => :text, :input_html => {:maxlength => 1200, :cols => "20", :rows => "6"}, :name => "cuerpo", label: false %>
	         <%= f.button :submit, :value => t('biomodelos.groups.experts.submit_btn'), :class => 'boton1', data: { disable_with: t('biomodelos.groups.experts.submit_btn') }%>
	   <% end %>
	</div>
<% end %>

<div id="group_users_tables"></div>

app/views/groups/group_activity.js.erb
$('#group_activity_table').html('<%=j render partial: 'groups/groups_activity' %>');

app/views/groups/index.html.erb
<div class="innercontainer fondoplumas nbg4" ng-controller="perfilCtrl">
	<div class="cajainners" id="style-1">
		<div class="hcbase">
			<h1><%= t('biomodelos.groups.index.title') %></h1>
			<%= link_to '', root_path, class: 'closecb' %>
			<% if user_signed_in? %>
				<a ng-click="newgroup=!newgroup; activeButton()" ng-class="{'btnact': isActive}" class="newgrbtn"><%= t('biomodelos.groups.suggest_group.title') %></a>
				<div ng-show="newgroup" class="forms clearfix">
					<p><%= t('biomodelos.groups.suggest_group.text') %></p>
					<%= simple_form_for :suggested_group, :url => {:controller => "groups", :action => "suggest_group" }, :html => {:class => 'forma' } do |f| %>
					    <%= f.input :name, :maxlength => 50, :placeholder => t('biomodelos.groups.suggest_group.group_name_ph'), label: false %>
					    <%= f.input :moderator, :maxlength => 50, :placeholder => t('biomodelos.groups.suggest_group.moderator_ph'), label: false %>
					    <%= f.input :content, :placeholder => t('biomodelos.groups.suggest_group.content_ph'), :as => :text, :input_html => {:maxlength => 600, :cols => "10", :rows => "6"}, label: false %>
					    <%= f.button :submit, :value => t('biomodelos.groups.suggest_group.submit_btn'), data: { disable_with: t('biomodelos.groups.suggest_group.submit_btn') } %>
					<% end %>
				</div>
			<% end %>
			<div class="sugeridor"></div>
			<div class="mt10"></div>
			<div class="aligner2">
				<% @groups.each do |group| %>
					<div class="groupcard">
						<div class="groupthumb">
						<%= link_to image_tag(group.logo.url(:thumb).to_s), group %>
						</div>
						<%= link_to group, :class => 'titgrcard' do%>
							<%= group.name %>
						<% end %>
						<div class="subtgr">
							<b><%= t('biomodelos.groups.index.moderator') %></b>
							</br>
							<%= group.admin.first ? group.admin.first.user.name : t('biomodelos.groups.index.no_moderator') %>
						</div>
						<div class="colhalf subtgr lineright">
							<b><%= t('biomodelos.groups.index.species') %></b>
							<h5><%= GroupsSpecies.where(group_id: group.id, groups_species_state_id: 1).count %></h5>
						</div>
						<div class="colhalf subtgr clearfix">
							<b><%= t('biomodelos.groups.index.members') %></b>
							<h5><%= GroupsUser.where(group_id: group.id, groups_users_state_id: 1).count %></h5>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/groups/show.html.erb
<div id="perfilCntrl" ng-controller="perfilCtrl" class="innercontainer bckgroup">
	<div class="perfilcont">
		<div class="col2">
			<h2><%= @group.name %></h2>
			<%= hidden_field_tag 'group_id_field', @group.id %>
			<% if @current_group_user && @current_group_user.is_admin %>
				<div ng-show="editgroup" class="editgroupform">
					<%= render 'groups/edit_group' %>
				</div>
				<div class="editgroupform" ng-show="messagebox">
				<h2><%= t('biomodelos.groups.group_message.title') %></h2>
				<%= simple_form_for :message, :url =>  groups_bulk_group_email_path, :method => :post do |f|  %>
					<%= f.input :message, :as => :text, :placeholder => t('biomodelos.groups.group_message.message_ph'), :input_html => {:maxlength => 500, :cols => "20", :rows => "8"}, :name => "cuerpo", label: false %>
					<%= f.hidden_field :group_id, :value => @group.id %>
				    <div class="clearfix"></div>
				    <%= f.submit t('biomodelos.groups.group_message.submit_btn'), class: "btngen ml0", data: { disable_with: t('biomodelos.groups.group_message.submit_btn') }%>
				    <a class="closeedit" ng-click="messagebox=!messagebox">X</a>
				<% end %>
				</div>
			<% end %>
			<div class="groupimg">
				<%= image_tag(@group.logo.url(:profile).to_s) %>
			</div>
			<div class="perflinks">
				<% if user_signed_in? %>
					<% if !@user_group %>
						<%= simple_form_for @groups_users do |f| %>
							<%= f.hidden_field :group_id, :value =>  @group.id %>
							<%= f.hidden_field :groups_users_state_id, :value => 2 %>
							<%= f.submit "", :class=> "joingroup", :title=>t('biomodelos.groups.profile.join_group_tt'), :rel=>"tooltip", data: { disable_with: "" } %>
						<% end %>
					<% elsif @user_group.groups_users_state_id == 2 %>
						<%= image_tag "groupjoin2.png", :title=>t('biomodelos.groups.profile.waiting_approval_tt'), :rel=>"tooltip" %>
					<% elsif @user_group.groups_users_state_id == 1 %>
						<%= link_to groups_user_path(@user_group), {method: :delete, data: { confirm: t('biomodelos.groups.profile.leave_group_confirm') }}  do %>
							<%= image_tag "leave.png", title:t('biomodelos.groups.profile.leave_group_tt'), class: 'leavegroup', rel: 'tooltip' %>
						<% end %>
						<% if @user_group.is_admin%>
							<a href="" title="<%= t('biomodelos.groups.profile.group_message_tt') %>" rel="tooltip" class="mailto" ng-click="messagebox=!messagebox"></a>
							<a href="" title="<%= t('biomodelos.groups.profile.edit_group_tt') %>" rel="tooltip" class="edituser" ng-click="editgroup=!editgroup"></a>
						<% end %>
					<% end %>
				<% end %>
			</div>

			<div class="clearfix"></div>
			<div class="perfilsub modertext"><%= t('biomodelos.groups.profile.moderators') %></div>
			<% @group_admins.each do |admin| %>
				<p class="moderlink"><a href="/users/<%= admin.user_id %>" class="moderlink"><%= admin.user.name %></a></p>
			<% end %>
			<div class="groupunder"><%= t('biomodelos.groups.profile.moderator_message') %></div>
			<p><%= @group.message %></p>
			<!-- <div class="groupunder">Última Actividad</div>
			<p class="actvspp"><a>Wingardium leviosa</a> · Aporte de Edición</p>
			<p class="actuser"><a>Norberto Lopez Alvarez</a> · 15/02/2016</p> -->
		</div>
		<div class="col1">

			<ul class="perfilnav groupnav">
		       	<li ng-class="{ active: isSet(1) }">
		          	<a href ng-click="setTab(1)"><%= t('biomodelos.groups.profile.statistics_tab') %></a>
		       	</li>
		       	<li ng-class="{ active: isSet(2) }">
		          	<a href ng-click="setTab(2)" class="group_tasks_tab"><%= t('biomodelos.groups.profile.tasks_tab') %></a>
		       	</li>
		       	<li ng-class="{ active: isSet(3) }">
		          	<a href ng-click="setTab(3)" class="group_activity_tab"><%= t('biomodelos.groups.profile.activity_tab') %></a>
		       	</li>
		       	<li ng-class="{ active: isSet(4) }">
		          	<a href ng-click="setTab(4)" class="group_species_tab"><%= t('biomodelos.groups.profile.species_tab') %></a>
		       	</li>
		       	<li ng-class="{ active: isSet(5) }">
		          	<a href ng-click="setTab(5)" class="group_users_tab"><%= t('biomodelos.groups.profile.experts_tab') %></a>
		       	</li>
		     </ul>

			<div ng-show="isSet(1)" class="cajaperfil scrollp">
				<%= render 'groups/groups_statistics' %>
			</div>
			<div ng-show="isSet(2)" class="cajaperfil group_tasks_box">
				<%= render 'groups/groups_tasks' %>
			</div>
			<div ng-show="isSet(3)" class="cajaperfil">
				<div id="group_activity_table"></div>
			</div>
			<div ng-show="isSet(4)" class="cajaperfil sppbox">
				<%= render 'groups/groups_species' %>
			</div>
			<div ng-show="isSet(5)" class="cajaperfil usrbox">
				<%= render 'groups/groups_users' %>
			</div>
		</div>
	</div>
</div>
<script>
$( ".tareaspp:odd" ).css( "background-color", "#f2f2f2" );
$(document).ready(function() {
	HomeControllerModule.typeahead_f();
});
</script>