config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|es/ do
    devise_for :users, controllers: { registrations: "registrations" }

    root 'home#show'

    get "species/autocomplete"
    get "species/visor"
    get "home/contact_us"
    get "home/about_us"
    get "home/publish"
    get "home/api"
    get "home/terms"
    post "home/send_contact_form"
    post "users_layers/load_layer"
    post "users_layers/pause_layer"
    post "users_layers/send_layer"
    post "reports/update_record"
    post "species/set_species"
    post "records/report_record"
    post "records/edit_record"
    post "records/new_form"
    post "records/show"
    post "species/species_info"
    post "records/send_report_record"
    post "models/load_initial_model"
    post "models/get_thresholds"
    post "models/get_hypotheses"
    post "models/download_model"
    post "models/download_terms"
    post "models/models_stats"
    get "models/metadata"
    get "records/records_metadata/:id" => "records#records_metadata", as: "records_metadata"
    get "species/search"
    post "ratings/rate_model"
    get "eco_variables/eco_variables_search"
    post "eco_variables/add_ecological_variable"
    get "species/:id/get_species_records" => "species#get_species_records"
    post "records/new_record"
    post "records/new_report"
    post "records/update_record"
    post "tasks/add_tasks"
    post "tasks/finish_task"
    post "tasks/tasks_by_group"
    post "tasks/tasks_by_user"
    post "groups_species/species_by_group"
    post "groups_species/update_groups_species"
    post "groups/bulk_group_email"
    post "groups/invite_user"
    post "groups/suggest_group"
    post "groups_users/users_by_group"
    post "groups_users/update_groups_user"
    post "users/send_message_to_user"
    post "groups/group_activity"
    post "home/upload_model"
    post "species/filter"
    get "geoserver/wms"
    get "geoserver/thumb"
    get "geoserver/continuous_thumb"
    get "geoserver/zip"
    get 'atlas/:filename', to: 'downloads#download'
    get '/downloads/generate_report', to: 'downloads#generate_report'
    get '/users', to: redirect('/%{locale}/users/sign_up')

 
    resources :users, :only => [:show]
    resources :groups, :only => [:index, :show, :update]
    resources :info, :only => [:index]
    resources :groups_species, :only => [:index, :create]
    resources :groups_users, :only => [:index, :create, :destroy]
    resources :tasks, :only => [:index, :create, :destroy]
    resources :ratings, :only => [:destroy]
    resources :models do
      member do
        get :metadata
      end
    end
  end
end

app/views/shared/_footer.html.erb
<footer>
		<div class="lbabfooter">
			<a href="http://www.humboldt.org.co" class="humboldtft" target="_blank">
				<%= image_tag("logohumboldt.png") %>
				<div class="humbname">
					<h1><%= t('biomodelos.footer.institute_html') %></h1>
					<h2><%= t('biomodelos.footer.program') %></h2>
				</div>
			</a>
		</div>
		<div class="sitemap">
			<nav>
				<ul id="subnav">
					<li>
						<%= link_to t('biomodelos.footer.publish'), home_publish_path %>
					</li>
					<li>
						<%= link_to t('biomodelos.footer.info'), info_index_path %>
					</li>
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Api', home_api_path %>
            </li>
          <% end %>
				</ul>
				<ul id="subnav">
					<li class="linehnav">
						<%= link_to t('biomodelos.footer.about'), home_about_us_path %>
					</li>
					<li>
						<%= link_to t('biomodelos.footer.terms'), home_terms_path %>
					</li>
					<li>
						<%= link_to t('biomodelos.footer.contact'), home_contact_us_path %>
					</li>
				</ul>
			</nav>
			<%= image_tag("logolba.png") %>
		</div>
</footer>

app/views/shared/_header.html.erb
<header>
	<%= link_to "BioModelos", root_path %>
	<%= hidden_field_tag 'locale_field', I18n.locale %>
	<nav class="menu">
		<ul class="active">
			<li><%= link_to t('biomodelos.header.home'), root_path %></li>
			<li><%= link_to t('biomodelos.header.models'), species_visor_path %></li>
			<li><%= link_to t('biomodelos.header.groups'), groups_path %></li>
			<% if user_signed_in? %>
			  <div class="usuario">
			    <%= link_to current_user.email, user_path(:id => current_user.id), :title=> t('biomodelos.header.profile_tt') %>
			    <%= hidden_field_tag 'user_name', current_user.name %>
			    <%= link_to '', destroy_user_session_path, :method=>'delete', :class=>'xsalir', :rel=> 'tooltip', :title=> t('biomodelos.header.log_out_tt') %>
			  </div>
			<% else %>
			    <li><%= link_to t('biomodelos.header.log_in'), new_user_session_path %></li>
			    <li><%= link_to t('biomodelos.header.sign_up'), new_user_registration_path %></li>
			<% end %>
		</ul>
		<a class="toggle-nav" href="#">&#9776;</a>
		<% if I18n.locale == :es %>
		  <%= link_to url_for(locale: :en), {class: 'lang', rel: 'tooltip', title: 'English'} do %>
		    en
		  <% end %>
		<% else %>
		  <%= link_to url_for(locale: :es), {class: 'lang', rel: 'tooltip', title:"Español"} do %>
		    es
		  <% end %>
		<% end %>
	</nav>
</header>

<script>
	$(document).ready(function(){
    $('.active li a').each(function(index) {
        if(this.href.trim() == window.location)
            $(this).addClass("current");
    });
});
</script>