config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|es/ do
    devise_for :users, controllers: { registrations: "registrations" }

    root 'home#show'

    get "species/autocomplete"
    get "species/visor"
    get "home/contact_us"
    get "home/about_us"
    get "home/publish"
    get "home/api"
    get "home/terms"
    post "home/send_contact_form"
    post "users_layers/load_layer"
    post "users_layers/pause_layer"
    post "users_layers/send_layer"
    post "reports/update_record"
    post "species/set_species"
    post "records/report_record"
    post "records/edit_record"
    post "records/new_form"
    post "records/show"
    post "species/species_info"
    post "records/send_report_record"
    post "models/load_initial_model"
    post "models/get_thresholds"
    post "models/get_hypotheses"
    post "models/download_model"
    post "models/download_terms"
    post "models/models_stats"
    get "models/metadata"
    get "records/records_metadata/:id" => "records#records_metadata", as: "records_metadata"
    get "species/search"
    post "ratings/rate_model"
    get "eco_variables/eco_variables_search"
    post "eco_variables/add_ecological_variable"
    get "species/:id/get_species_records" => "species#get_species_records"
    post "records/new_record"
    post "records/new_report"
    post "records/update_record"
    post "tasks/add_tasks"
    post "tasks/finish_task"
    post "tasks/tasks_by_group"
    post "tasks/tasks_by_user"
    post "groups_species/species_by_group"
    post "groups_species/update_groups_species"
    post "groups/bulk_group_email"
    post "groups/invite_user"
    post "groups/suggest_group"
    post "groups_users/users_by_group"
    post "groups_users/update_groups_user"
    post "users/send_message_to_user"
    post "groups/group_activity"
    post "home/upload_model"
    post "species/filter"
    get "geoserver/wms"
    get "geoserver/thumb"
    get "geoserver/continuous_thumb"
    get "geoserver/zip"
    get 'atlas/:filename', to: 'downloads#download'
    get '/downloads/generate_report', to: 'downloads#generate_report'
    get '/users', to: redirect('/%{locale}/users/sign_up')

 
    resources :users, :only => [:show]
    resources :groups, :only => [:index, :show, :update]
    resources :info, :only => [:index]
    resources :groups_species, :only => [:index, :create]
    resources :groups_users, :only => [:index, :create, :destroy]
    resources :tasks, :only => [:index, :create, :destroy]
    resources :ratings, :only => [:destroy]
    resources :models do
      member do
        get :metadata
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!, :except => [:show, :about_us, :contact_us, :send_contact_form, :terms, :api]

	def show
	end

	def about_us
	end

	def publish
		@publication = Publication.new
	end

	def upload_model
		@publication = Publication.new(upload_params)

	    if @publication.save
	      AdministratorsMailer.model_uploaded(current_user, @publication).deliver_now
	      redirect_to home_publish_path, notice: I18n.t('biomodelos.publish.success_notice')
	    else
	      render 'publish'
	    end
  	end

	def contact_us
	end

	def send_contact_form
		@contact_message = ContactMessage.new(message_params)
		recaptcha_v3_valid = verify_recaptcha(action: 'contact_us', minimum_score: 0.9, secret_key: Rails.application.credentials.dig(:recaptcha, :RECAPTCHA_SECRET_KEY_V3))
		recaptcha_v2_valid = verify_recaptcha unless recaptcha_v3_valid

		if @contact_message.valid?
			if recaptcha_v3_valid || recaptcha_v2_valid
				AdministratorsMailer.contact_us(@contact_message).deliver_now
				redirect_to root_path, notice: I18n.t('biomodelos.contact.success_notice')
			else
				if !recaptcha_v3_valid
					@show_checkbox_recaptcha = true
				end
				render :contact_us
			end
		else
			errores = I18n.t('biomodelos.contact.fields_error')
			if !@contact_message.errors.messages[:name].blank?
				errores << "Nombre | "
			end
			if !@contact_message.errors.messages[:email].blank?
				errores << "E-mail | "
			end
			if !@contact_message.errors.messages[:content].blank?
				errores << "Mensaje | "
			end
			redirect_to home_contact_us_path, :flash => { :error => errores }
		end
	end

	def terms
	end

	private

	    def message_params
	      params.require(:contact_message).permit(:name, :email, :subject, :content)
	    end

	    def upload_params
	      params.require(:publication).permit(:cc_license, :records_vis, :sib_contact, :files, :atlas_agreement, :terminos).merge(user_id: current_user.id)
	    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<div class="innercontainer aboutbg">
	<div class="centerbox" id="centerbox">
		<div class="scrolledContent mb30 scrolledPadding">
			<div class="maintitle">
				BioModelos
			</div>
			<div class="slogan">
				<%= t('biomodelos.home.slogan') %>
			</div>
			<div class="mb30"> <%= image_tag("Animatedworld.gif") %></div>
			<p><%= t('biomodelos.about_us.text_1_html') %></p>
			<div class="subt">
				<%= t('biomodelos.about_us.team') %>
			</div>
			<div class="equipo">
				<div class="member">
				<%= image_tag("fototenorio.png") %>
				ELKIN TENORIO</br>
				<%= t('biomodelos.about_us.thematic') %>
				</div>
				<div class="member">
				<%= image_tag("fotonerieth.png") %>
				NERIETH LEURO</br>
				<%= t('biomodelos.about_us.thematic') %>
				</div>
				<div class="member">
				<%= image_tag("fotojuanrey.png") %>
				JUAN CARLOS REY</br>
				<%= t('biomodelos.about_us.thematic') %>
				</div>
				<div class="member">
				<%= image_tag("fotoerika.png") %>
				ERIKA SUAREZ</br>
				<%= t('biomodelos.about_us.developer') %>
				</div>
				<div class="member">
				<%= image_tag("fotocamilo.png") %>
				CAMILO ZAPATA</br>
				<%= t('biomodelos.about_us.developer') %>
				</div>
				<div class="member">
				<%= image_tag("fotojorge.png") %>
				JORGE LUIS HIGUITA</br>
				<%= t('biomodelos.about_us.developer') %>
				</div>
				<div class="member">
				<%= image_tag("fotocesar.png") %>
				CÉSAR GUTIÉRREZ</br>
				<%= t('biomodelos.about_us.frontend') %>
				</div>
				<div class="member">
				<%= image_tag("fotohelena.png") %>
				HELENA OLAYA</br>
				<%= t('biomodelos.about_us.productowner') %>
				</div>
				<div class="member">
				<%= image_tag("fotolaura.png") %>
				LAURA GARCIA</br>
				<%= t('biomodelos.about_us.network') %>
				</div>
			</div>
			<div class="subt">
				<%= t('biomodelos.about_us.board') %>
			</div>
				<div class="member">
				<%= image_tag("fotolina.png") %>
				LINA SÁNCHEZ</br>
				</div>
				<div class="member">
				<%= image_tag("fotomariac.png") %>
				MARÍA CECILIA LONDOÑO</br>
				</div>
				<div class="member">
				<%= image_tag("fotoelkin.png") %>
				ELKIN NOGUERA</br>
				</div>
			<div class="subt">
				<%= t('biomodelos.about_us.founders') %>
			</div>
			<div class="member">
				MARÍA CECILIA LONDOÑO</br>
				JORGE VELÁSQUEZ</br>
				IVÁN GONZÁLEZ</br>
				DANIEL LÓPEZ</br>
				CÉSAR GUTIÉRREZ</br>
			</div>
			<div class="subt">
				<%= t('biomodelos.about_us.acknowledgments') %>
			</div>
            <div class="member_align">
                <div class="member">
                    <b><%= t('biomodelos.about_us.thematic') %></b></br>
                    CARLOS JAIR MUÑOZ</br>
                    CRISTIAN CRUZ</br>
                    GABRIEL PERILLA</br>
                    LUIS ROMERO</br>
                    HÉCTOR MANUEL ARANGO</br>
                </div>
                <div class="member">
                    <b><%= t('biomodelos.about_us.developer') %></b></br>
                    MANUEL GALVEZ</br>
                    DANIEL LÓPEZ</br>
                    RICARDO BASTIDAS</br>
                    VALENTINA GRAJALES</br>
                    RICARDO REYES</br>
                    ALEJANDRO MORENO</br>
                </div>
                <div class="member">
                    <b><%= t('biomodelos.about_us.photovid') %></b></br>
                    FELIPE VILLEGAS</br>
                    ANDRÉS FELIPE DUARTE</br>
                    BIA HUMBOLDT</br>
                </div>
            </div>
			<div class="subt mb30">
				<%= t('biomodelos.about_us.awards') %>
			</div>
			<div class="aliados">
				<%= link_to image_tag("premio.png"), "https://minciencias.gov.co/sala_de_prensa/por-primera-vez-se-premian-iniciativas-ciencia-abierta", target: "_blank" %>
			</div>
			<div class="aliados">
				<%= link_to image_tag("medalla.png"), "http://www.humboldt.org.co/es/actualidad/item/1414-programa-biomodelos-recibe-medalla-humboldt-caldas-2019", target: "_blank" %>
			</div>
			<div class="subt">
				<%= t('biomodelos.about_us.sponsors') %>
			</div>
				<div class="logos">
					<%= link_to image_tag("logoMA.png"), "https://www.minambiente.gov.co/", target: "_blank" %>
				</div>
				<div class="logos">
					<%= link_to image_tag("logoMC.png"), "https://www.minciencias.gov.co/", target: "_blank" %>
				</div>
				<div class="logos">
					<%= link_to image_tag("logoFA.png"), "https://www.fondoadaptacion.gov.co/", target: "_blank" %>
				</div>
				<div class="logos">
					<%= link_to image_tag("logoGEE.png"), "https://earthengine.google.com/", target: "_blank" %>
				</div>
				<div class="logos">
					<%= link_to image_tag("logoNASA.png"), "https://www.nasa.gov/", target: "_blank" %>
				</div>
				<div class="logos">
					<%= link_to image_tag("logoGBIF.png"), "https://www.gbif.org/", target: "_blank" %>
				</div>
			<div class="subt">
				<%= t('biomodelos.about_us.allies') %>
			</div>
				<div class="aliados">
					<%= link_to image_tag("LogosSIB.png"), "https://biodiversidad.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoscm.png"), "https://mamiferoscolombia.org/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logocalidris.png"), "https://calidris.org.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("LogosAPC.png"), "https://www.asoprimatologicacolombiana.org/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoach.png"), "https://www.acherpetologia.org/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoASICTIOS.png"), "https://acictios.org/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoACO.png"), "https://asociacioncolombianadeornitologia.org/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoSelva.png"), "https://www.selva.org.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoJBM"), "https://www.botanicomedellin.org/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoINVEMAR.png"), "https://www.invemar.org.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logounal.png"), "https://unal.edu.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoJaveriana.png"), "https://www.javeriana.edu.co/inicio", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoAntioquia.png"), "https://www.udea.edu.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoCordoba.png"), "https://www.unicordoba.edu.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoCauca.png"), "https://www.unicauca.edu.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoUnivalle.png"), "https://www.univalle.edu.co/", target: "_blank" %>
				</div>
				<div class="aliados">
					<%= link_to image_tag("logoAMNH.png"), "https://www.amnh.org/", target: "_blank" %>
				</div>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
	$('#centerbox').niceScroll(".scrolledContent", {
		cursorcolor: "#5d5e5e",
		cursorwidth: "7px",
		cursorborder: "none"
	});
});
</script>

app/views/home/api.html.erb
<% # Open API Specification hasn't resolve the internationalization issue. We'll have to mantain two spec files until then.%>
<head>
  <style>
    [data-role=redoc-description] p {
      margin-bottom: 10px;
    }
    #redoc-container {
      height: -moz-calc(100% - 190px);
      height: -webkit-calc(100% - 190px);
      height: calc(100% - 190px);
      overflow: scroll;
    }
    .scrollbar-container > div:first-of-type  {
      bottom: 135px !important;
    }
    .scrollbar-container span:first-of-type {
      text-transform: uppercase;
    }
    .scrollbar-container li label:hover, .scrollbar-container li label.active {
      color:#db3f2a;
    }
    .api-content > div {
      padding: 30px 0 5px;
    }
    .api-content h1 {
      text-transform: uppercase;
      color:#db3f2a;
    }
    .api-content h2 {
      color:#1b3337;
    }
    .api-content p a {
      color: #db3f2a;
    }
    .api-content p a:hover {
      color: tomato;
    }

  </style>
</head>
<body>

  <div id="redoc-container"></div>
  <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"></script>
  <script>
    Redoc.init('<%="/api_spec_#{I18n.locale}.yml"%>', {
      hideDownloadButton: true,
      theme: {
        typography: {
          fontFamily: 'Lato',
          fontSize: '16px'
        }
      }
    }, document.getElementById('redoc-container'))
    //Config options: https://github.com/Redocly/redoc#redoc-theme-object
  </script>
</body>

app/views/home/contact_us.html.erb
<div class="innercontainer fondoplumas nbg3">
	<div class="cajainners">
            <div class="hcbase">
                  <h1><%= t('biomodelos.contact.title') %></h1>
                  <%= link_to '', root_path, class: 'closecb' %>
                  <div id="mailform" class="forms">
                        <%= simple_form_for :contact_message, :url =>  home_send_contact_form_path, :method => :post do |f| %>
                              <%= f.error_notification %>
                              <%= f.input :name, :maxlength => 50, :placeholder => t('biomodelos.contact.name_ph'), :name => "nombre", label: false%>
                              <%= f.input :subject, :maxlength => 50, :placeholder => t('biomodelos.contact.subject_ph'), :name => "asunto", label: false %>
                              <%= f.input :email, :maxlength => 50, :placeholder => "E-mail", :name => "email", label: false %>
                              <%= f.input :content, :as => :text, :input_html => {:maxlength => 1200, :cols => "20", :rows => "12"}, :name => "cuerpo", label: false %>
                              <% if @show_checkbox_recaptcha %>
                                    <%= recaptcha_tags %>
                              <% else %>
                                    <%= recaptcha_v3(action: 'contact_us', site_key: Rails.application.credentials.dig(:recaptcha, :RECAPTCHA_SITE_KEY_V3)) %>
                              <% end %>
                              <%= f.button :submit, :value => t('biomodelos.contact.submit_btn'), :class => 'boton1', data: { disable_with: t('biomodelos.contact.submit_btn') }%>
                        <% end %>
                        <p><strong><%= t('biomodelos.contact.address') %>:</strong> calle 28A no. 15-09 Bogotá D.C., Colombia.</br>
                        <a href="mailto:biomodelos@humboldt.org.co">biomodelos@humboldt.org.co</a></p>
                  </div>
            </div>
	</div>
</div>

app/views/home/show.html.erb
<div class="innercontainer" ng-controller="homeCtrl as hc">
	<div class="homeline" ng-style="{'background-image': hc.slide}">
		<div class="container homec">
			<%= form_tag({}, {:id => 'search_form_home'})  do %>
				<%= text_field_tag :query, '', :id => 'search_form', :placeholder => t('biomodelos.home.search_ph'), :include_blank => false, :rel => 'autocomplete' %>
				<%= hidden_field_tag 'species_id_home' %>
				<%= submit_tag '', :name => nil, :class => 'searchbtnhome', :id => 'searchBtnHome', :title => t('biomodelos.home.go_to_species_tt'), :rel => "tooltip" %>
			<% end %>

			<div class="hlbtn">
				<a ng-click="consulta=!consulta"><%= t('biomodelos.home.models_btn') %></a>
				<a ng-click="contribuye=!contribuye"><%= t('biomodelos.home.contribute_btn') %></a>
				<a ng-click="publica=!publica"><%= t('biomodelos.home.publish_btn') %></a>
				<%= link_to t('biomodelos.home.advanced_search'), species_visor_path(:search => "1") %>
			</div>
		</div>
	</div>
	<h1><%= t('biomodelos.home.slogan') %></h1>
	<div class="allgraphs">
		<div class="graphcont">
			<h3><%= t('biomodelos.home.mammals') %></h3>
			<h4 id="mam_lbl"></h4>
			<div class="graph" id="donutmam" style="width: 140px; height: 180px;"></div>
			<%= image_tag("home_mam.png") %>
		</div>
		<div class="graphcont">
			<h3><%= t('biomodelos.home.birds') %></h3>
			<h4 id="av_lbl"></h4>
			<div class="graph" id="donutave" style="width: 140px; height: 180px;"></div>
			<%= image_tag("home_ave.png") %>
		</div>
		<div class="graphcont">
			<h3><%= t('biomodelos.home.reptiles') %></h3>
			<h4 id="rep_lbl"></h4>
			<div class="graph" id="donutrep" style="width: 140px; height: 180px;"></div>
			<%= image_tag("home_rep.png") %>
		</div>
		<div class="graphcont">
			<h3><%= t('biomodelos.home.amphibians') %></h3>
			<h4 id="anf_lbl"></h4>
			<div class="graph" id="donutanf" style="width: 140px; height: 180px;"></div>
			<%= image_tag("home_anf.png") %>
		</div>
		<div class="graphcont">
			<h3><%= t('biomodelos.home.fish') %></h3>
			<h4 id="pec_lbl"></h4>
			<div class="graph" id="donutpec" style="width: 140px; height: 180px;"></div>
			<%= image_tag("home_pec.png") %>
		</div>
		<div class="graphcont">
			<h3><%= t('biomodelos.home.invertebrates') %></h3>
			<h4 id="inv_lbl"></h4>
			<div class="graph" id="donutinv" style="width: 140px; height: 180px;"></div>
			<%= image_tag("home_inv.png") %>
		</div>
		<div class="graphcont">
			<h3><%= t('biomodelos.home.plants') %></h3>
			<h4 id="pla_lbl"></h4>
			<div class="graph" id="donutpla" style="width: 140px; height: 180px;"></div>
			<%= image_tag("home_pla.png") %>
		</div>
	<h3> <%= t(".models_status_text")%> </h3>
	</div>
	<!-- 	<div class="barhome" id="gruposbar" style="width: 800px; height: 30px;"></div> -->
	<div ng-show="consulta">
		<div class="cajabase">
			<div class="hcbase">
				<h1><%= t('biomodelos.home.consult.title') %></h1>
				<a ng-click="consulta=!consulta" class="closecb">x</a>
			</div>
			<p><%= t('biomodelos.home.consult.text_1') %></p></br>
			<%= link_to t('biomodelos.home.consult.go_btn'), species_visor_path(:search => "1"),  class: 'botoncb' %>
			<p><%= t('biomodelos.home.consult.text_2') %></p>
		</div>
	</div>

	<div ng-show="contribuye">
		<div class="cajabase">
			<div class="hcbase">
				<h1><%= t('biomodelos.home.contribute.title') %></h1>
				<a ng-click="contribuye=!contribuye" class="closecb">x</a>
			</div>
			<p><%= t('biomodelos.home.contribute.text_1') %></p></br>
			<%= link_to t('biomodelos.home.contribute.sign_up_btn'), new_user_registration_path, class: 'botoncb' %>
			<h3><%= t('biomodelos.home.contribute.contribution_types') %></h3>
			<p><%= t('biomodelos.home.contribute.text_2') %></br>
			<%= t('biomodelos.home.contribute.activities_list_html') %></br>
			</p>
			<% if user_signed_in? %>
			    <%= link_to t('biomodelos.home.contribute.profile_btn'), user_path(:id => current_user.id), class: 'botoncb' %>
			    <%= hidden_field_tag 'user_name', current_user.name %>
			<% else %>
			    <%= link_to t('biomodelos.log_in.log_in_btn'), new_user_session_path, class: 'botoncb' %>
			<% end %>
		</div>
	</div>

	<div ng-show="publica">
		<div class="cajabase">
			<div class="hcbase">
				<h1><%= t('biomodelos.home.publish.title') %></h1>
				<a ng-click="publica=!publica" class="closecb">x</a>
			</div>
			<p><%= t('biomodelos.home.publish.text_1') %> <a href="/publicacion.pdf" target="_blank"><%= t('biomodelos.home.publish.more_lnk') %></a></br></br>
			<%= t('biomodelos.home.publish.text_2') %></p>
			<%= link_to t('biomodelos.home.publish.publish_btn'), home_publish_path, class: 'botoncb' %>
		</div>
	</div>

	<div ng-hide="news" style="display:none">
		<div class="cajanews">
			<div class="hcbase2">
				<h1><%= t('biomodelos.home.news.title') %></h1>
				<a ng-click="news=!news" class="closecb">x</a>
			</div>
			<%= image_tag("home_news.png") %>
			<p><%= t('biomodelos.home.news.text_1') %></p></br>
			<p><%= t('biomodelos.home.news.text_2') %></br><a href="http://repository.humboldt.org.co/handle/20.500.11761/35544" target="_blank">http://repository.humboldt.org.co/handle/20.500.11761/35544</a></p>
		</div>
	</div>
</div>

<script>
$(document).ready(function() {
	HomeControllerModule.typeahead_f();
	HomeControllerModule.google_charts_f();
});
</script>

app/views/home/terms.html.erb
<div class="innercontainer aboutbg">
	<div class="centerbox" id="centerbox">
		<div id="scrolledContent" class="scrolledPadding">
			<div class="maintitle">
				BioModelos
			</div>
			<div class="slogan">
				<%= t('biomodelos.terms.title') %>
			</div>
			<a href="#general" class="btnterminos"><%= t('biomodelos.terms.general') %></a>
			<a href="#politica" class="btnterminos"><%= t('biomodelos.terms.sign_up') %></a>
			<a href="#publicacion" class="btnterminos"><%= t('biomodelos.terms.publish') %></a>
			<div class="subt" id="general">
				<%= t('biomodelos.terms.general') %>
			</div>
			<p class="smallp"><i><%= t('biomodelos.terms.general_text') %></i></p>
			<div class="thirdtitle"><b>1.</b> <%= t('biomodelos.terms.general') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_1_text') %></p>
			<div class="thirdtitle"><b>2.</b> <%= t('biomodelos.terms.general_2_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_2_text_html') %>
			</p>
			<div class="thirdtitle"><b>3.</b> <%= t('biomodelos.terms.general_3_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_3_text_html') %>
			</p>
			<div class="thirdtitle"><b>4.</b> <%= t('biomodelos.terms.general_4_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_4_text_html') %>
			</p>
			<div class="thirdtitle"><b>5.</b> <%= t('biomodelos.terms.general_5_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_5_text_html') %>
			</p>
			<div class="thirdtitle"><b>6.</b> <%= t('biomodelos.terms.general_6_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_6_text_html') %></p>
			<div class="thirdtitle"><b>7.</b> <%= t('biomodelos.terms.general_7_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_7_text_html') %>
			</p>
			<div class="thirdtitle"><b>8.</b> <%= t('biomodelos.terms.general_8_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_8_text_html') %></p>
			<div class="thirdtitle"><b>9.</b> <%= t('biomodelos.terms.general_9_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.general_9_text_html') %></br></br>
			<div class="specialp">Instituto de investigación de recursos biológicos Alexander von Humboldt – Gerencia de Información Científica</br>
			Avenida Paseo Bolívar 16 - 20</br>
			Bogotá, Colombia</br>
			Tel: +57 (1) 3202767</br>
			E-mail: biomodelos@humboldt.org.co</div>
			</p>

			<div class="subt" id="politica">
				<%= t('biomodelos.terms.sign_up') %>
			</div>
			<p class="smallp"></p>
			<div class="thirdtitle"><b>1.</b><%= t('biomodelos.terms.sign_up_1_title') %></b></div>
			<p class="smallp"><%= t('biomodelos.terms.sign_up_1_text_html') %>
			</p>
			<div class="thirdtitle" id="personales"><b>2.</b><%= t('biomodelos.terms.sign_up_2_title') %></div>
			<p class="smallp"><%= t('biomodelos.terms.sign_up_2_text_html') %></p>

			<div class="subt" id="publicacion">
				<%= t('biomodelos.terms.publish') %>
			</div>
			<div class="thirdtitle"><b>1.</b> <%= t('biomodelos.terms.publish_1_title') %></div>
			<p class="smallp specialp"><%= t('biomodelos.terms.publish_1_text_html') %></p>
			<div class="thirdtitle"><b>2.</b> <%= t('biomodelos.terms.publish_2_title') %></div>
			<p class="smallp specialp"><%= t('biomodelos.terms.publish_2_text_html') %></p>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
	$('#centerbox').niceScroll('#scrolledContent', {
		cursorcolor: "#5d5e5e",
		cursorwidth: "7px",
		cursorborder: "none"
	});
});
</script>